// Bebidas de COSECHA — isomorfo a ING en data.js.
// costo = suma del escandallo de docs/RECETARIO_BEBIDAS.md
// precio = ceil(costo * COSTOS_OPERATIVOS / MARGEN_DIVISOR), la fórmula de la casa.
// 'receta' apunta al encabezado de la ficha en el recetario.
export const BEB = [
  {cat:'bebida', sub:'agua', id:'BE01', nombre:"Arándano y romero", ml:500, kcal:68, prot:1, carb:16, gras:0.3, costo:33.96, precio:56, receta:'BE-01', alergenos:["Ninguno"], objetivo:null, addonProteina:true},
  {cat:'bebida', sub:'agua', id:'BE02', nombre:"Pepino y hierbabuena", ml:500, kcal:62, prot:2, carb:13, gras:0.3, costo:12.95, precio:22, receta:'BE-02', alergenos:["Ninguno"], objetivo:'definicion', addonProteina:true},
  {cat:'bebida', sub:'agua', id:'BE03', nombre:"Fresa y jengibre", ml:500, kcal:69, prot:1, carb:16, gras:0.4, costo:16.48, precio:28, receta:'BE-03', alergenos:["Ninguno"], objetivo:null, addonProteina:true},
  {cat:'bebida', sub:'agua', id:'BE04', nombre:"Toronja, albahaca y sal de mar", ml:500, kcal:54, prot:1, carb:13, gras:0.1, costo:10.89, precio:18, receta:'BE-04', alergenos:["Ninguno"], objetivo:'recuperacion', addonProteina:false},
  {cat:'bebida', sub:'agua', id:'BE05', nombre:"Piña, chía y hierbabuena", ml:500, kcal:116, prot:2, carb:20, gras:3.2, costo:11.97, precio:20, receta:'BE-05', alergenos:["Semilla de chía (no es alérgeno mayor declarable en México; se lista por transparencia de método)"], objetivo:'definicion', addonProteina:false},
  {cat:'bebida', sub:'agua', id:'BE06', nombre:"Jamaica en frío", ml:500, kcal:68, prot:1, carb:16, gras:0, costo:7.60, precio:13, receta:'BE-06', alergenos:["Ninguno"], objetivo:null, addonProteina:false},
  {cat:'bebida', sub:'cafe', id:'BE07', nombre:"Espresso Doble", ml:36, kcal:3, prot:0, carb:1, gras:0.1, costo:8.72, precio:15, receta:'BE-07', alergenos:[], objetivo:'definicion', addonProteina:false},
  {cat:'bebida', sub:'cafe', id:'BE08', nombre:"Latte", ml:256, kcal:143, prot:7, carb:11, gras:7.5, costo:13.73, precio:23, receta:'BE-08', alergenos:["lacteos (leche de vaca)"], objetivo:null, addonProteina:false},
  {cat:'bebida', sub:'cafe', id:'BE09', nombre:"Cappuccino", ml:146, kcal:73, prot:4, carb:6, gras:3.8, costo:10.69, precio:18, receta:'BE-09', alergenos:["lacteos (leche de vaca)"], objetivo:null, addonProteina:false},
  {cat:'bebida', sub:'cafe', id:'BE10', nombre:"Cold Brew", ml:280, kcal:5, prot:0, carb:1, gras:0.1, costo:12.87, precio:22, receta:'BE-10', alergenos:["lacteos (proteina de suero) unicamente en la version con addon de proteina"], objetivo:'definicion', addonProteina:true},
  {cat:'bebida', sub:'cafe', id:'BE11', nombre:"Espresso Coconut Cloud", ml:176, kcal:149, prot:1, carb:9, gras:11.8, costo:21.50, precio:36, receta:'BE-11', alergenos:["coco (clasificado como fruto seco por la FDA; declarar en carta)","lacteos (proteina de suero) unicamente en la version con addon de proteina"], objetivo:null, addonProteina:true},
  {cat:'bebida', sub:'cafe', id:'BE12', nombre:"Matcha Latte", ml:285, kcal:174, prot:8, carb:20, gras:7, costo:18.89, precio:32, receta:'BE-12', alergenos:["lacteos (leche de vaca)"], objetivo:null, addonProteina:false},
  {cat:'bebida', sub:'cafe', id:'BE13', nombre:"Dirty Chai Latte", ml:296, kcal:135, prot:5, carb:17, gras:5.2, costo:19.62, precio:33, receta:'BE-13', alergenos:["lacteos (leche de vaca)"], objetivo:null, addonProteina:false},
  {cat:'bebida', sub:'cafe', id:'BE14', nombre:"Horchata Cold Brew", ml:290, kcal:90, prot:1, carb:15, gras:2.8, costo:18.82, precio:31, receta:'BE-14', alergenos:["nuez (fruto seco) en la horchata","lacteos (proteina de suero) unicamente en la version con addon de proteina"], objetivo:null, addonProteina:true},
  {cat:'bebida', sub:'smoothie', id:'BE15', nombre:"Berry Protein", ml:470, kcal:289, prot:28, carb:24, gras:8.9, costo:41.41, precio:69, receta:'BE-15', alergenos:["leche (requeson, leche descremada, aislado de suero)"], objetivo:'definicion', addonProteina:true},
  {cat:'bebida', sub:'smoothie', id:'BE16', nombre:"Cacao Peanut", ml:440, kcal:656, prot:40, carb:76, gras:21, costo:37.62, precio:62, receta:'BE-16', alergenos:["cacahuate","leche (leche entera, aislado de suero)","cereal con gluten por contaminacion cruzada (avena no certificada sin gluten)"], objetivo:'volumen', addonProteina:true},
  {cat:'bebida', sub:'smoothie', id:'BE17', nombre:"Mango Coconut", ml:480, kcal:392, prot:28, carb:66, gras:1.5, costo:44.30, precio:73, receta:'BE-17', alergenos:["leche (aislado de suero)","coco (clasificado como fruto seco por la FDA; declarar en carta)"], objetivo:'recuperacion', addonProteina:false},
  {cat:'bebida', sub:'smoothie', id:'BE18', nombre:"Vanilla Matcha", ml:420, kcal:292, prot:30, carb:25, gras:8.1, costo:40.47, precio:67, receta:'BE-18', alergenos:["pepita de calabaza (semilla) - no es alergeno de declaracion obligatoria en la NOM-051 pero se declara por politica de casa","chicharo (leguminosa) - idem","coco (clasificado como fruto seco por la FDA; declarar en carta)"], objetivo:'definicion', addonProteina:false},
  {cat:'bebida', sub:'smoothie', id:'BE19', nombre:"Mamey", ml:450, kcal:429, prot:31, carb:62, gras:6.3, costo:45.89, precio:76, receta:'BE-19', alergenos:["leche (yogur griego, leche descremada, aislado de suero)","pepita de calabaza (semilla) - no obligatoria en NOM-051, se declara por politica de casa"], objetivo:null, addonProteina:true},
];
export const BEB_SUB_LABEL = {agua:'Aguas y limonadas', cafe:'Barra de café', smoothie:'Smoothies con proteína'};

// Modificador que se vende sobre el resto de la carta, no es una bebida.
export const BEB_ADDON = {id:'ADD-PROT', nombre:"PROTEIN +25", ml:30, kcal:104, prot:25, carb:0, gras:0.2, costo:14.74, precio:25, alergenos:["Leche (proteína de suero): no apto para alergia a la proteína de leche","Lactosa: menos de 0,5 g por dosis, tolerable para la mayoría de intolerantes, pero se declara","Lecitina de girasol (agente instantizante del aislado)","Trazas de soya si el lote se instantiza con lecitina de soya en vez de girasol: exigir al proveedor lote con lecitina de girasol","Sin gluten, sin frutos secos, sin huevo"]};
